name: Deploy Search Api

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: 'fa-developerschallenges'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20'

jobs:
  deploy-search-api:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
